# Dockerfile.frontend-build
FROM node:24.2.0-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Optional: If you want to inspect the output, uncomment:
# RUN ls -la /app/dist
