# Stage 1: Build Vue app
FROM node:24.2.0-alpine

# Set working dir
WORKDIR /app

# Install deps
COPY package*.json ./
RUN npm install

# Copy everything else
COPY . .
RUN npm run build

# Stage 2: Serve with NGINX
FROM nginx:alpine

# Remove default NGINX static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy built frontend files
COPY --from=builder /app/build /usr/share/nginx/html

# Copy custom NGINX config
COPY nginx.conf /etc/nginx/conf.d/default.conf
