version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://prosaurus.com
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
