# This file (docker-compose.yml) is the base file for both the override and prod files
# it does not include certain aspects of either prod or override file such as the start command

services:
  frontend:

    build:
      # The directory where we look for a Dockerfile
      context: ./frontend

    # Set the working directory inside the container at _run_ time
    working_dir: /app

    volumes:
      # Sets the frontend folder to be the app folder in the container
      - ./frontend:/app
      # Isolates the node_modules folder in the contain from the host
      - /app/node_modules
    
    networks:
      # use the app-network
      - app-network

    environment:
      # backend URL accessible from frontend
      NODE_ENV: ${NODE_ENV}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}


  backend:

    build:
      # The directory where we look for a Dockerfile
      context: ./backend

    # Set the working directory inside the container at _run_ time
    working_dir: /app

    volumes:
      # sets the backend folder to be the app folder in the container
      - ./backend:/app
      # Isolates the node_modules folder in the contain from the host
      - /app/node_modules
      # encryption folders, with read only option
      - ./backend/etc/encrypt:/etc/letsencrypt:ro

    networks:
      # use the app-network
      - app-network

    environment:
      # Defines the variable for _run_ time use
      NODE_ENV: ${NODE_ENV}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}

  reverse-proxy:
    # Note: the reverse-proxy service is based on an image therefore no build phase
    image: nginx:alpine

    volumes:
      # nginx configuration file
      - ./backend/etc/nginx/nginx-docker.conf:/etc/nginx/nginx.conf:ro
      # site-enapled folder
      - ./backend/etc/nginx/sites-enabled-docker:/etc/nginx/sites-enabled-docker:ro
      # encryption folders, with read only option
      - ./backend/etc/encrypt:/etc/letsencrypt:ro

    ports:
      # Expose HTTPS port for reverse proxy to handle SSL
      - "8443:443"
      # Expose HTTP port used for redirecting to HTTPS
      - "8080:80"

    networks:
      # use the app-network
      - app-network

    depends_on:
      # Front end service dependeny
      - frontend
      # Back end service dependency
      - backend

    # Entry point which turns the daemon off (GPT says it's not needed, we shall see)
    entrypoint: nginx -g 'daemon off;'

networks:

  # The internal network all the containers use
  app-network:
    # the network's name
    name: app-network
    # Type of connection it uses
    driver: bridge