version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /app/node_modules   # Prevent node_modules from being overwritten
    environment:
      NODE_ENV: development
