# Dockerfile.nginx
FROM nginx:alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom nginx config
COPY ./backend/etc/nginx/nginx-production.conf /etc/nginx/nginx.conf

# Copy Vue build output into nginx public dir
COPY ./frontend-dist /usr/share/nginx/html

# Optional: Copy static files if you have them
# COPY static /usr/share/nginx/html/static
